Added a framework for accurate and efficient simulation of SiDB logic
marcelwa/fiction pull request #105
Opened 2023-02-01 10:58 UTC by Drewniok

✨ Added a framework for accurate and efficient simulation of SiDB logic.

2023-02-01 11:36 UTC, Drewniok commented on include/fiction/technology/charge_distribution_surface.hpp
> +class charge_distribution_surface<Lyt, false> : public Lyt
we added the copy assignment constructor, but rule of three?

2023-02-01 11:38 UTC, Drewniok commented on include/fiction/technology/sidb_charge_state.hpp
> +[[nodiscard]] std::string charge_configuration_to_string(const std::vector<sidb_charge_state> &charge_distribution) noexcept
sorry, I forgot to include ``vector``. My fault!

2023-02-02 09:43 UTC, marcelwa requested changes

2023-02-02 15:32 UTC, marcelwa commented on include/fiction/algorithms/simulation_sidb/time_to_solution.hpp
> +void sim_acc_tts(charge_distribution_surface<Lyt>& lyt, exgs_stats<Lyt>& result_exact,
Why is this function calling `quicksim` itself but requires the user to pass `exgs_stats` from a previous run? Can it not call that itself too?

2023-02-02 15:32 UTC, marcelwa commented on include/fiction/algorithms/simulation_sidb/check_groundstate.hpp
> +    return std::abs(min_energy_exact - min_energy_new_ap) / min_energy_exact < 0.00001;
Didn't you define the `POP_STABILITY_ERR` constant for this?

2023-02-03 09:13 UTC, marcelwa approved these changes

2023-02-03 09:17 UTC, merged