🐛 Bug fixes and improvements related to the coordinate system
marcelwa/fiction pull request #225
Opened 2023-05-25 15:58 UTC by wlambooy

## Description

This PR is a collection of bug fixes in order to make the experience working with layouts of different coordinate types more seamless. In particular, the following changes are introduced:

* All coordinate types now have a `wrap` function added to their respective namespaces that takes a dimension coordinate. When the coordinate is beyond the given dimension, it wraps to the next coordinate within the dimension. If no such coordinate exists, it becomes a dead copy of the dimension coordinate.
* Coordinate iteration now does not go into an infinite loop when an out of bounds iterator is given.
* Area and volume computation is now dependent on the coordinate type
* Cartesian layouts with SiQAD coordinates now always represent full dimer rows; this means that the z dimension is always 1.
* An `integral_abs` function defined on integral number types was added to `math_utils.hpp`. Simply using `std::abs` could give an ambiguity error or a compiler warning when applied to an unsigned integer. This function handles these concerns such that it can be applied to any integral number type without compiler errors or warnings.
* Addition and subtraction is now defined properly on SiQAD coordinates.
* `static_assert` checks were added to `apply_gate_layout` and `relative_to_absolute_cell_position`, making sure that the `CellLyt` template parameter is not based in SiQAD coordinates.
* Some changes to the docs: the `siqad` namespace in `coordinates.hpp` had missing docs; the "Offset coordinates are required" line was removed from `cartesian_layout.hpp`.
* In `layout_utils.hpp`, converting between SiQAD and fiction coordinates now appropriately resizes the layout. Note that since layouts with SiQAD coordinates must always have full dimer rows, the area of the transformed layout is not always equal to the area of the original layout when converting _to_ SiQAD coordinates. The tests have thus been updated accordingly.
* The `print_charge_layout` function was adapted to the new changes. Also layout cropping is now optional (default false).

Tests were added for all of the new behaviour. The `wrap` function implementations are tested through the coordinate iterator tests.

## Checklist:

- [x] The pull request only contains commits that are related to it.
- [x] I have added appropriate tests and documentation.
- [x] I have made sure that all CI jobs on GitHub pass.
- [x] The pull request introduces no new warnings and follows the project's style guidelines.

2023-05-25 16:40 UTC, marcelwa requested changes
Many thanks for these great additions and fixes. Looks very good overall. You have really improved the code stability! Just a couple of minor comments from my side here.

2023-05-25 16:40 UTC, marcelwa commented on include/fiction/layouts/coordinates.hpp
> +     */
I don't think I understand the docstring text yet. Could you maybe rephrase it and also add a quick note on the use case of this function?

2023-05-25 16:40 UTC, marcelwa commented on test/io/print_layout.cpp
> +        std::stringstream print_stream{};
You should be able to declare the stream outside of the sections. This would prevent the duplicate.

2023-05-25 16:40 UTC, marcelwa commented on test/layouts/cartesian_layout.cpp
> +}
Please make sure that all files end with a newline.

2023-05-25 16:40 UTC, marcelwa commented on test/layouts/cartesian_layout.cpp
> +    CHECK(lyt{aspect_ratio<lyt>{9, 9}}.z() == 1);
Just for completeness, also add one check that initializes the layout with an aspect ratio that already has a z value of 1.

2023-05-25 16:40 UTC, marcelwa commented on test/layouts/coordinates.cpp
> +            }
Please remove debug output

2023-05-25 16:40 UTC, marcelwa commented on test/layouts/coordinates.cpp
> +TEST_CASE("Addition / subtraction of cube coordinates", "[coordinates]")
This says "cube coordinates" but uses SiQAD coordinates. Which one is correct?

2023-05-25 16:40 UTC, marcelwa commented on test/utils/math_utils.cpp
> +}
see above

2023-05-26 13:44 UTC, wlambooy commented
It seems that some compilers generate a warning when the result of the new abs function is casted to an integer. Apparently they do not take the type traits check for integrality into account. I will the support for floating point values from this function as this can be achieved without ambiguity using `std::fabs`, making the intended use to be able to take the abs of any integral type number without compiler warnings.

2023-05-26 14:24 UTC, wlambooy commented
Windows CI build is out of heap space again 🙄

2023-06-02 15:35 UTC, marcelwa requested changes
Looks essentially done. I just spotted a small inconsistency. After this, it's done, I promise :laughing:

2023-06-02 15:35 UTC, marcelwa commented on include/fiction/utils/math_utils.hpp
> +T integral_abs(const T n)
```suggestion
T integral_abs(const T n) noexcept
```

2023-06-02 15:35 UTC, marcelwa commented on include/fiction/utils/math_utils.hpp
>  T round_to_n_decimal_places(const T number, const uint64_t n)
I know you didn't touch this one, but could you add `noexcept` for consistency?

```suggestion
T round_to_n_decimal_places(const T number, const uint64_t n) noexcept
```

2023-06-02 21:10 UTC, marcelwa approved these changes
Many thanks!

2023-06-02 21:10 UTC, merged